linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    exclude-functions:
      # Writing to stderr - if this fails, we can't report it anyway
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Fprint
      # Closing files/pipes in defer - nothing useful to do on error
      - (*os.File).Close
      - io.Copy
      # Cleanup in tests
      - os.RemoveAll

issues:
  exclude-use-default: false
